version: '3'
services:
    wordpress:
        image: visiblevc/wordpress:0.17.0-php7.2
        ports:
            - 8080:80
        volumes:
            # Database
            - ./data:/data
            # Plugins
            - ./wp-content/plugins/fanciest-author-box:/app/wp-content/plugins/fanciest-author-box
            # Themes
            - ./dist:/app/wp-content/themes/aliem
            - ./wp-content/themes/Avada:/app/wp-content/themes/Avada
            # Uploads
            - ./wp-content/uploads:/app/wp-content/uploads
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            DB_USER: root
            PLUGINS: >-
                academic-bloggers-toolkit,
                [abt-deprecated-peer-review]https://github.com/dsifford/abt-deprecated-peer-review/archive/master.zip,
                broken-link-checker,
                co-authors-plus,
                disqus-comment-system,
                jetpack,
                mce-table-buttons,
                search-by-algolia-instant-relevant-results,
                shortcodes-ultimate,
                w3-total-cache,
                wp-smushit,
                wordpress-seo,
                query-monitor,
            URL_REPLACE: https://www.aliem.com,http://localhost:8080
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG: 'true'
            ALIEM_API_KEY: ${ALIEM_API_KEY}

    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 22222:80
volumes:
    data:
