version: '3.7'
services:
    wordpress:
        image: visiblevc/wordpress:0.22.0-php7.3
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        environment:
            DB_NAME: aliem
            DB_PASS: root
            DB_USER: root
        volumes:
            - ./data:/data
            - ./wp-content/plugins/fanciest-author-box:/app/wp-content/plugins/fanciest-author-box
            - ./wp-content/plugins/instagram-feed-pro:/app/wp-content/plugins/instagram-feed-pro
            - ./wp-content/uploads:/app/wp-content/uploads

    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - data:/var/lib/mysql
        ports:
            - 22222:80

    redis:
        image: redis

volumes:
    data:
