version: '3'
services:
    wordpress:
        environment:
            ALIEM_API_KEY: ${ALIEM_API_KEY?ALIEM_API_KEY key not defined in .env}
            DB_NAME: aliem
            DB_PASS: root
            DB_USER: root
            PLUGINS: >-
                academic-bloggers-toolkit
                [abt-deprecated-peer-review]https://github.com/dsifford/abt-deprecated-peer-review/archive/master.zip
                broken-link-checker
                co-authors-plus
                disqus-comment-system
                jetpack
                mce-table-buttons
                search-by-algolia-instant-relevant-results
                shortcodes-ultimate
                w3-total-cache
                wordpress-seo
                wp-smushit
        image: visiblevc/wordpress:0.18.0-php7.2
        volumes:
            - ./data:/data
            - ./wp-content/plugins/fanciest-author-box:/app/wp-content/plugins/fanciest-author-box
            - ./wp-content/uploads:/app/wp-content/uploads

    db:
        environment:
            MYSQL_ROOT_PASSWORD: root
        image: mariadb:10
        volumes:
            - data:/var/lib/mysql

    phpmyadmin:
        environment:
            MYSQL_ROOT_PASSWORD: root
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80
volumes:
    data:
